---
- name: Install Tigera Operator
  ansible.builtin.command: kubectl apply --server-side --force-conflicts -f https://raw.githubusercontent.com/projectcalico/calico/{{ calico_version }}/manifests/tigera-operator.yaml
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  register: operator_result
  changed_when: "'created' in operator_result.stdout"

- name: Create Custom Resource for Calico
  ansible.builtin.copy:
    dest: /tmp/calico-config.yaml
    content: |
      apiVersion: operator.tigera.io/v1
      kind: Installation
      metadata:
        name: default
      spec:
        calicoNetwork:
          ipPools:
          - blockSize: 26
            cidr: {{ pod_network_cidr }}
            encapsulation: VXLANCrossSubnet
            natOutgoing: Enabled
            nodeSelector: all()

      ---

      apiVersion: operator.tigera.io/v1
      kind: APIServer
      metadata:
        name: default
      spec: {}

- name: Apply Calico configuration
  ansible.builtin.command: kubectl apply -f /tmp/calico-config.yaml
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  register: apply_result
  changed_when: "'created' in apply_result.stdout or 'configured' in apply_result.stdout"