users:
  - default # Используем стандартного пользователя ubuntu
  - name: ansible
    gecos: Ansible Automation User
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: true
    ssh_authorized_keys:
      - "YOUR_PUBLIC_KEY"

write_files:
  - path: /etc/profile.d/01-kubectl-alias.sh
    owner: root:root
    permissions: '0644'
    content: |
      alias k='kubectl'
      # Настройка автодополнения для алиаса k
      source <(kubectl completion bash)
      complete -o default -F __start_kubectl k

runcmd:
  - [ systemctl, reload, ssh ]
  - apt-get update
  - apt-get install -y bash-completion